Added How it works text to button
praveenscience/easya-website pull request #35
Opened 2021-05-29 04:35 UTC by kanishka8276

Solves issue #16
Added How it works text in the link on the home page

2021-05-29 12:51 UTC, praveenscience requested changes

2021-05-29 12:51 UTC, praveenscience commented on src/components/Home/_Child247.js
> +           How It works
Can we please have this translated, thanks.

2021-05-31 14:41 UTC, praveenscience commented
Any updates on this? 🤔

2021-05-31 14:42 UTC, kanishka8276 commented
> Any updates on this? 🤔

No , Not yet

2021-05-31 15:04 UTC, merged

2021-05-31 15:04 UTC, praveenscience commented
@kanishka8276 I have merged it anyway... I don't want you to lose points, at least you took it up! 😊

2021-05-31 15:09 UTC, kanishka8276 commented
> @kanishka8276 I have merged it anyway... I don't want you to lose points, at least you took it up! 😊

Thanks a lot 😀